all : DiskSchedulingSimulation.class FCFSAlgorithm.class ScheduleAlgorithm.class ScheduleAlgorithmBase.class CLOOKAlgorithm.class CSCANAlgorithm.class LOOKAlgorithm.class SCANAlgorithm.class SSTFAlgorithm.class 

clean :
	-rm *.class 2> /dev/null

DiskSchedulingSimulation.class : DiskSchedulingSimulation.java
	javac DiskSchedulingSimulation.java

FCFSAlgorithm.class : FCFSAlgorithm.java
	javac FCFSAlgorithm.java

ScheduleAlgorithm.class : ScheduleAlgorithm.java
	javac ScheduleAlgorithm.java

ScheduleAlgorithmBase.class : ScheduleAlgorithmBase.java
	javac ScheduleAlgorithmBase.java

LOOKAlgorithm.class : LOOKAlgorithm.java
	javac LOOKAlgorithm.java

CLOOKAlgorithm.class : CLOOKAlgorithm.java
	javac CLOOKAlgorithm.java

CSCANAlgorithm.class : CSCANAlgorithm.java
	javac CSCANAlgorithm.java

SCANAlgorithm.class : SCANAlgorithm.java
	javac SCANAlgorithm.java

SSTFAlgorithm.class : SSTFAlgorithm.java
	javac SSTFAlgorithm.java
